version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todolist
      - DB_USERNAME=admin
      - DB_PASSWORD=laravel
    networks:
      - todolist-network
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"

  db:
    image: mysql:8.0
    container_name: todolist-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: laravel
    volumes:
      - my-todolist-mysql-data:/var/lib/mysql
    networks:
      - todolist-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-plaravel"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  todolist-network:
    driver: bridge

volumes:
  my-todolist-mysql-data:
    driver: local 